### ISSUE TITLE
Why print and not pp?

### ISSUE THREAD

**Issue by rgrinberg** [dbuenzli/uuidm#1]
`pp` seems to be the convention in your other libs. Wondering why you shied away from it here.

**Comment by dbuenzli** [comment]
Because this was written in june 2008.

**Comment by rgrinberg** [comment]
Ah yes, you must have been distracted by the financial crisis and made this mistake. Perhaps we could add `pp` as an alias though?

**Comment by dbuenzli** [comment]
Why not ?
