### ISSUE TITLE
Optional parameter for custom & random v1 node ID

### ISSUE THREAD

**Issue by ghost** [dbuenzli/uuidm#4]
According to [rfc4122#section-4.1.6](https://tools.ietf.org/html/rfc4122#section-4.1.6):

> For systems with no IEEE address, a randomly or pseudo-randomly
> generated value may be used; see Section 4.5.  The multicast bit must
> be set in such addresses, in order that they will never conflict with
> addresses obtained from network cards.

**Comment by dbuenzli** [comment]
What is your problem and what are you suggesting ? `v1` uuid are explicitly not supported due to privacy concerns.

**Comment by ghost** [comment]
I'm considering time based UUIDs for my project but with a randomly generated node so as to avoid the privacy issue. I'm not sure if v5 can be used in this way.

**Comment by dbuenzli** [comment]
Ah indeed `uuidm` only supports name-based uuids. Do you want to make use of the structure of the uuids ? Depending on your context I'm not sure you'd really gain something w.r.t. devising your own uuid scheme, but if you have anything more concrete to propose I can have a look.

**Comment by ghost** [comment]
[Context](https://gitlab.com/orbifx/logarion/blob/master/src/meta.ml#L91).

I'm contemplating the idea of having UUIDs which are the combination of a randomly generated node value for the node, and the time a note was made. This could use the space better, than a totally random generated UUID.

I could implement that by passing values to v5, or I could reuse the special case mentioned in the RFC of random node value. Any thoughts?

**Comment by dbuenzli** [comment]
> I could implement that by passing values to v5,

I don't see how you can achieve this.

Did you actually estimate the real space gains you'd get on a typical usage scenario ? Is it really worth the added complexity ? The structure of uuids seems rather arcane to me and if you want to provide some kind of interop. scenario, you could make the life of other easier by not doing this.

Personally I would devise my own uuid scheme here if you really want something that is based on time + random. I'm not even sure whether time based UUIDs lexicographical order would be compatible with time order (I didn't check) which you could guarantee with your own scheme (e.g. RFC 3339 time stamp appended with `-$(rand)`.

**Comment by dbuenzli** [comment]
> RFC 3339 time stamp

In UTC.

**Comment by ghost** [comment]
Ok, will look into that.

**Comment by dbuenzli** [comment]
I'll close this for now. Feel free to continue the discussion or reopen if you think you really need something.
