### ISSUE TITLE
Build fails in opam install uuidm

### ISSUE THREAD

**Issue by etherealvisage** [dbuenzli/uuidm#7]
Hi,

The following relevant output is from a clean opam environment using OCaml 4.02.0:

    # + ocamlfind ocamlc -c -g -bin-annot -safe-string -package cmdliner -package bytes -I test -I src -o test/uuidtrip.cmo test/uuidtrip.ml
    # File "test/uuidtrip.ml", line 85, characters 8-13:
    # Error: Unbound value const
    # Hint: Did you mean cos or cosh?
    # Command exited with code 2.

For the moment I worked around it by removing the `uuidtrip.ml` file but that's obviously not a long-term solution. Any further information I can give to help? I'm no ocaml expert, just wanted to use another program installed via opam.

Thanks!

**Comment by dbuenzli** [comment]
This is a missing contraint in the opam file. I suspect you have `cmdliner < 0.9.8` installed. You should be able to work around by installing at least v0.9.8 by doing `opam install cmdliner.0.9.8`.

**Comment by etherealvisage** [comment]
That did it! Thanks for the quick response. :-)

**Comment by dbuenzli** [comment]
Thanks for the report. A fix is on its way to the opam repo.
